# version of docker-compose syntax
version: '3.7'

services:

  app:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - production_static_data:/vol/web
    expose:
      - "443"
    env_file:
      - .debug.env


  proxy:
    build:
      context: ./proxy_production
    volumes:
      - production_static_data:/vol/static
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app

volumes:
  production_static_data: