# version of docker-compose syntax
version: '3.7'

services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_development_data_volume:/var/lib/mysql
    env_file:
      - .debug.env

  app:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - development_static_data:/vol/web
    depends_on:
      - db
    expose:
      - "443"
    env_file:
      - .debug.env


  proxy:
    build:
      context: ./proxy_development
    volumes:
      - development_static_data:/vol/static
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app

volumes:
  development_static_data:
  mysql_development_data_volume: