# Generated by Django 3.2 on 2021-04-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('birthYear', models.IntegerField(blank=True, null=True)),
                ('deathYear', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField(editable=False)),
                ('date_modified', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date_added', models.DateField(editable=False)),
                ('date_modified', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileUrl', models.FileField(upload_to='books')),
                ('coverImgUrl', models.FileField(blank=True, null=True, upload_to='book-covers')),
                ('title', models.CharField(max_length=512)),
                ('fileType', models.CharField(blank=True, max_length=32, null=True)),
                ('language', models.CharField(blank=True, max_length=24, null=True)),
                ('copyright', models.BooleanField(default=False)),
                ('date_added', models.DateField(editable=False)),
                ('date_modified', models.DateField()),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='core.Author')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='core.Genre')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
