# version of docker-compose syntax
version: '3.7'

services:

  app:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - development_static_data:/vol/web
    env_file:
      - .debug.env


  proxy:
    build:
      context: ./proxy_development
    volumes:
      - development_static_data:/vol/static
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  development_static_data: